version: '2'
services:
    pubstrack-app:
        image: pubstrack
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://pubstrack-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=pubstrack
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pubstrack-mongodb:
        extends:
            file: mongodb.yml
            service: pubstrack-mongodb
